### ISSUE TITLE
In v1.8.3, The command does not work on Intel Macs.

### ISSUE THREAD

**Issue by TakaakiAndo1** [justjavac/dvm#124]
As the title says.

I installed v1.8.3 today with the following command, but when I run the command, nothing shows up.
I have already confirmed that v1.8.2 works.

```zsh
$ curl -fsSL https://deno.land/x/dvm/install.sh | sh
... (omission) ...
Dvm was installed successfully to /Users/takaaki.ando/.dvm/bin/dvm
Run 'dvm --help' to get started.
$ dvm -V
$ dvm list
$ dvm install 1.23.3
```

Thanks.

**Comment by justjavac** [comment]
fixed in #123. I will release v1.8.4 now
