### ISSUE TITLE
What is the purpose of environment variable `$DENO_INSTALL` in the install script?

### ISSUE THREAD

**Issue by amorphobia** [justjavac/dvm#127]
The install script sets the environment variable and adds `$DENO_INSTALL/bin` to user's path.

I thought it would be used by Deno's binary, and had a look at the Deno manual. There was only `DENO_INSTALL_ROOT`.

So it's used by `dvm` itself. However, the Deno binaries are installed to `$DVM_DIR/bin`. Neither could I find any lines in the source code that read / write the environment `DENO_INSTALL`.

Thanks for your reply.

**Comment by CGQAQ** [comment]
This env variable is nothing to do with DVM now, it should have been removed a long time ago, just nobody realized about it
