### ISSUE TITLE
can't install the latest version

### ISSUE THREAD

**Issue by oliyg** [justjavac/dvm#16]
can't install the latest version:

`dvm install 0.40.0`

and it output:

Deno v0.40.0 is not yet released or available.

**Comment by pythys** [comment]
It seems this bug is still not resolved.

`dvm install 1.0.1`

Deno v1.0.1 is not yet released or available

**Comment by pythys** [comment]
Submitted PR to resolve the issue -> https://github.com/justjavac/dvm/pull/17
