### ISSUE TITLE
Deno is not installed while it's correclty installed on MacOS

### ISSUE THREAD

**Issue by antoine-pous** [justjavac/dvm#176]
Hi,

when i'm installing deno everything is ok, files are well created
```console
$ dvm install
Installing deno v1.15.3 from cache...
replace /Users/user/.dvm/versions/v1.15.3/deno? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
Deno v1.15.3 has installed.
```

But when i'm trying to use deno, i'm encountering this error.
```console
$ dvm use
Deno 1.15.3 is not installed, you can run 'dvm install 1.15.3' to install it.
```

I'm using a `.dvmrc` file

**Comment by CGQAQ** [comment]
@antoine-pous what's the version of `dvm` are you using?

**Comment by CGQAQ** [comment]
you are using a very old version, the prompt was changed here <https://github.com/justjavac/dvm/commit/99ac3a8d4eaf89b0f086fb03cb0ed274d4e11717#diff-ee724fb2846cba8c44ba1e188510fe132d5464ff0d2125cb6db5181fa1c9591fL46-L50>
