### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by marcjal** [justjavac/dvm#18]
Hi 👋 friends I would like to know if after install the `dvm` command I have to add it to the PATH or something like that because I after install the `dvm` I tried to run `deno --version` and in the terminal appears one message related a permission I'm running again with `sudo` and later another message that says `deno: command not found`.

I'm using `zsh and macos`.

Thanks

**Describe the bug**

**To Reproduce**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Screenshots**

### Versions

You can get this information from copy and pasting the output of `dvm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Additional context**

**Comment by justjavac** [comment]
fixed. Rewrite using rust
