### ISSUE TITLE
The requested URL returned error: 403

### ISSUE THREAD

**Issue by fveracoechea** [justjavac/dvm#185]
Not able to install DVM at the moment:

```bash
curl -fsSL https://dvm.deno.dev | sh
curl: (22) The requested URL returned error: 403
```

Also, the website https://dvm.deno.dev/ is down:

<img width="782" alt="image" src="https://github.com/justjavac/dvm/assets/26258895/b9d0a34b-cf15-473e-b9da-f9f7201e7e70">

**Comment by justjavac** [comment]
> Hey justjavac,
> 
> The 'justjavac' account on Deno Deploy has exceeded 100% of the outbound data usage limit for the current billing cycle.
> 
> This account is currently on the free plan. This plan includes 100 GiB per month, all of which have been used. The billing cycle resets on 2023-11-09 at 11:25:04.
> 
> Because the usage limits have been exceeded, processing of requests for this account has been suspended until the start of the next billing cycle.
> 
> To resume service, you can upgrade to a pro plan.

😭
