### ISSUE TITLE
Version registry is out of date

### ISSUE THREAD

**Issue by SergeiMinaev** [justjavac/dvm#187]
[This project](https://github.com/denoland/dotland) is archived so [version registry](https://raw.githubusercontent.com/denoland/dotland/main/versions.json) is not updated anymore. 

One possible solution is to get versions from https://crates.io/api/v1/crates/deno but I'm not sure if it's allowed to use crates api this way.

**Comment by justjavac** [comment]
https://api.github.com/repos/denoland/deno/releases
