### ISSUE TITLE
Install script does not install latest dvm version

### ISSUE THREAD

**Issue by jerome-benoit** [justjavac/dvm#199]
1. `curl -fsSL https://dvm.deno.dev | sh`
2. `dvm --version` -> dvm 1.8.6 instead of dvm 1.8.8

**Comment by jerome-benoit** [comment]
@justjavac: are you sure the two are related? 

#200 will fix the installation of the latest deno version, not the installation of the latest dvm version with the install script ...

**Comment by zingmane** [comment]
issue still exists with version 1.9.0
