### ISSUE TITLE
dvm install does not work on MAC OS X to install any version of Deno

### ISSUE THREAD

**Issue by apatrida** [justjavac/dvm#22]
**Describe the bug**

`dvm install` always results in an error on my MAC OS X 10.15.4

**To Reproduce**

1. `dvm install latest` or `dvm install 1.2.0`

**Expected behavior**

I expect Deno to be installed.  Instead no matter what (clean `.dvm` dir, no `.dvm` dir) I get an error that the directory exists, which is itself created by dvm before it reports that error.

```
 dvm install latest
  downloading [====================] 100% 0.0s
Extracting gz contents
Error extracting archive
Error: ENOTEMPTY: directory not empty, rmdir '/Users/jminard/.dvm/latest'
    at Object.rmdirSync (fs.js:789:3)
    at /Users/jminard/WebstormProjects/untitled1/node_modules/dvm/bin/dvm.js:410:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '/Users/jminard/.dvm/latest'
} latest
```

removing the directory does not solve the problem, `dvm` will recreate the directory and then complain it already exists.

### Versions

* 0.3.1

**Comment by wenjoy** [comment]
I also encounter this issue

**Comment by alexdohmen** [comment]
I guess there is a , `{ recursive: true }` missing

**Comment by alexdohmen** [comment]
https://github.com/justjavac/dvm/pull/23

**Comment by justjavac** [comment]
fixed. Rewrite using rust
