### ISSUE TITLE
dvm should not attempt to replace /usr/bin/deno

### ISSUE THREAD

**Issue by KSXGitHub** [justjavac/dvm#29]
## Problem

Before I use dvm, I have install `deno-bin` from the Arch User Repository (`/usr/bin/deno`). When I try using dvm to install another deno version, it emits `Permission denied (os error 13)`. I guess it is because dvm attempted to replace `/usr/bin/deno`.

## Current Workaround

Uninstall `deno-bin`.

**Comment by justjavac** [comment]
How did you install deno to the `/usr/bin/deno` directory, did you use `sudo`?
