### ISSUE TITLE
install.sh doesn't work for .zshrc with a symbolic link

### ISSUE THREAD

**Issue by 4strodev** [justjavac/dvm#57]
I have my zsh configuration managed by stow. That saves your dotfiles in a separate folder and create a symlink to folder where the file was previously. Probably it is the problem I dont know.

When I try to install dvm the script detects that my default shell is bash and my default shell is zsh. So I have to take the ENV variables and put it to my zshrc.

**Comment by justjavac** [comment]
Does Deno's official installer work properly? https://github.com/denoland/deno_install

**Comment by 4strodev** [comment]
Currently I am using arch linux and I can install deno with pacman. But I didn't try to install with the official installer

**Comment by justjavac** [comment]
I tried using **stow** to manage dotfiles (on ubuntu), it can be installed normally. Can you provide a detailed error message?

**Comment by 4strodev** [comment]
I will try to use dvm again.

**Comment by InSuperposition** [comment]
I am seeing a similar issues with both dvm and the deno installer, the script excute successfully with no error messages but the binary is not in path. I have a i7 Macbook with fresh install of OSX Monterey. I am able to install deno via homebrew and paths work correctly.
