### ISSUE TITLE
Bug: Can not find deno

### ISSUE THREAD

**Issue by Weilet** [justjavac/dvm#66]
Can not find deno, It seems that `use_.rs` do not set right environment variable
![image](https://user-images.githubusercontent.com/32561597/164029199-296e1d46-6a2c-4523-a7b0-7a1ca520dc5b.png)

**Comment by justjavac** [comment]
@cgqaq

**Comment by Weilet** [comment]
#67 install.ps1 do not set right environment variables, and I try to fix it, please review it
